### ISSUE TITLE
Dorada

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2023_Analysis_15-matf-chicken-invaders#1]
Po dogovoru na junskoj odbrani, moguce je dodati novi alat i doraditi postojece. Odbrana bi bila u julskom ispitnom roku u terminu ispita iz FP. Javite mi se ako zelite da upisem poene sa junske odbrane (moze kao odgovor u ovom tiketu) ili ako zelite da branite opet.

**Comment by TamaraDjukic** [comment]
Izvinjavam se na kasnom odgovoru, ali dolazim da dopunim projekat u terminu fp-a, koji  je danas.
